name: DigitalOcean App Push
on: [push]
jobs:
  digital-ocean-deploy:
    runs-on: ubuntu-latest
    name: Deploy App
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: DigitalOcean App Platform deployment
      uses: digitalocean/app_action@main
      with:
        app_name: mevius-mevway
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

