name: DigitalOcean App Push
on: [push]
jobs:
  digital-ocean-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GITHUB_SHA
        id: github-sha
        shell: bash
        run: |
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          echo "::set-output name=sha::$SHORT_SHA"
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.5
        with:
            app_name: mevius-mevway
            token: '${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}'
            images: '[{"name": "mevway","image":{"registry_type": "DOCR","repository": "mevway","tag": "${{steps.github-sha.outputs.sha}}"}}]'
