name: DigitalOcean App Push
on: [push]
jobs:
  digital-ocean-deploy:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@v1.1.5
        with:
            app_name: mevius-mevway
            token: '${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}'
            images: '[{"name": "mevway","image":{"registry_type": "DOCR","repository": "mevway","tag": "${{ steps.commit.outputs.short }}"}}]'

