name: DigitalOcean App Push
on: [push]
jobs:
  digital-ocean-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@main
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build container image
        run: docker build -t $DIGITALOCEAN_REG_NAME/$DIGITALOCEAN_REPO_NAME:$(echo $GITHUB_SHA | head -c7) .
      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Push image to DigitalOcean Container Registry
        run: docker push $DIGITALOCEAN_REG_NAME/$DIGITALOCEAN_REPO_NAME:$(echo $GITHUB_SHA | head -c7)
        
